[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "balsam-undialable-provider"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "4"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "5"
      search_records = "true"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-passive"
  [groups.instances]
    count = 80
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "6"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-provider"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "7"
      record_count = "1"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["balsam"]
  [groups.run]
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "10"
      expect_dht = "false"
      group_order = "8"
      search_records = "true"
      timeout_secs = "600"
      undialable = "false"

[[groups]]
  id = "cypress-passive"
  [groups.instances]
    count = 35
    percentage = 0.0
  [groups.build]
    selectors = ["cypress"]
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-provider"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["cypress"]
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "2"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["cypress"]
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      bs_strategy = "3"
      bucket_size = "10"
      group_order = "3"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 16
    percentage = 0.0
  [groups.build]
    selectors = ["cypress"]
  [groups.run]
    [groups.run.test_params]
      alpha = "6"
      bootstrapper = "true"
      bs_strategy = "1"
      bucket_size = "10"
      group_order = "0"
      timeout_secs = "600"
