[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 150
  concurrent_builds = 0
  builder = "docker:go"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "balsam"
  builder = "docker:go"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 0
    percentage = 0.0
  [groups.build_config]
    enabled = true
    exec_pkg = "."
    go_version = "1.19"
    module_path = "github.com/libp2p/test-plans/dht"
  [groups.build]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      target = ""
      version = "v0.18.0"

    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-cid"
      target = ""
      version = "v0.3.2"
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.0"
      n_bootstrap = "-4"
      n_paths = "10"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "200"

[[groups]]
  id = "cypress"
  builder = "docker:go"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 0
    percentage = 1.0
  [groups.build_config]
    enabled = true
    exec_pkg = "."
    go_version = "1.19"
    module_path = "github.com/libp2p/test-plans/dht"
  [groups.build]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      target = ""
      version = "v0.18.0"

    [[groups.build.dependencies]]
      module = "github.com/ipfs/go-cid"
      target = ""
      version = "v0.3.2"
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_bootstrap = "-4"
      n_paths = "0"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "200"
