[metadata]
  name = "find-peers-01"
  author = "raulk"

[global]
  plan = "dht"
  case = "find-peers"
  total_instances = 50
  concurrent_builds = 0
  builder = "exec:go"
  runner = "local:exec"
  disable_metrics = false

[[groups]]
  id = "bootstrappers"
  builder = "exec:go"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    enabled = true
    exec_pkg = "."
    module_path = "github.com/libp2p/test-plans/dht"
  [groups.build]
    selectors = ["foo"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      target = ""
      version = "995fee9e5345fdd7c151a5fe871252262db4e788"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      target = ""
      version = "76944c4fc848530530f6be36fb22b70431ca506c"
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      n_bootstrap = "1"
      random_walk = "true"

[[groups]]
  id = "peers"
  builder = "exec:go"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 49
    percentage = 0.0
  [groups.build_config]
    enabled = true
    exec_pkg = "."
    module_path = "github.com/libp2p/test-plans/dht"
  [groups.build]
    selectors = ["bar", "bee"]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      n_bootstrap = "1"
      random_walk = "true"
